services:
  react:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app/
    volumes:
      - ../app:/usr/src/app:cached
      - /run/host-services/ssh-auth.sock:/ssh-agent #SSHエージェントのソケットをマウント

    environment:
      - SSH_AUTH_SOCK=/ssh-agent # コンテナ内でSSHソケットを利用
    stdin_open: true
    tty: true
